const tiendas = [
  { id: 1, nombre: "Tienda del Coto 10", precioTortilla: 21, precioMasa: 19, precioTotopos: 18 },
  { id: 2, nombre: "Ávila", precioTortilla: 20, precioMasa: 18, precioTotopos: 18 },
  { id: 3, nombre: "Six", precioTortilla: 19, precioMasa: 17, precioTotopos: 18 },
  { id: 4, nombre: "Octavio", precioTortilla: 20, precioMasa: 18, precioTotopos: 18 },
  { id: 5, nombre: "Paty Cópala", precioTortilla: 20, precioMasa: 18, precioTotopos: 18 },
  { id: 6, nombre: "Abarrotes Ópalo", precioTortilla: 22, precioMasa: 20, precioTotopos: 18 },
  { id: 7, nombre: "Alice", precioTortilla: 20, precioMasa: 18, precioTotopos: 18 },
  { id: 8, nombre: "Coto 1", precioTortilla: 20, precioMasa: 18, precioTotopos: 18 },
  { id: 9, nombre: "Carnicería de Ramón", precioTortilla: 20, precioMasa: 18, precioTotopos: 18 },
  { id: 10, nombre: "Tienda del Mesón", precioTortilla: 23, precioMasa: 21, precioTotopos: 18 },
  { id: 11, nombre: "Doña Mary Deptos.", precioTortilla: 23, precioMasa: 21, precioTotopos: 18 },
  { id: 12, nombre: "Karina", precioTortilla: 20, precioMasa: 18, precioTotopos: 18 },
  { id: 13, nombre: "Yoco", precioTortilla: 19, precioMasa: 17, precioTotopos: 18 },
  { id: 14, nombre: "Alma", precioTortilla: 23, precioMasa: 21, precioTotopos: 18 },
  { id: 15, nombre: "Carnicería Jacobo", precioTortilla: 21, precioMasa: 19, precioTotopos: 18 },
  { id: 16, nombre: "Rosy", precioTortilla: 23, precioMasa: 21, precioTotopos: 18 },
  { id: 17, nombre: "Abarrotes de la Abue", precioTortilla: 21, precioMasa: 19, precioTotopos: 18 },
  { id: 18, nombre: "Abarrotes Alondra", precioTortilla: 20, precioMasa: 18, precioTotopos: 18 },
  { id: 19, nombre: "Don Beto", precioTortilla: 21, precioMasa: 19, precioTotopos: 18 },
  { id: 20, nombre: "Tienda del Ejido", precioTortilla: 19, precioMasa: 17, precioTotopos: 18 },
  { id: 21, nombre: "Señora de Mirador", precioTortilla: 22, precioMasa: 20, precioTotopos: 18 },
  { id: 22, nombre: "Don Migue", precioTortilla: 22, precioMasa: 20, precioTotopos: 18 },
  { id: 23, nombre: "Abarrotes El Chino", precioTortilla: 22, precioMasa: 20, precioTotopos: 18 },
  { id: 24, nombre: "Quebec", precioTortilla: 22, precioMasa: 20, precioTotopos: 18 },
  { id: 25, nombre: "10441 Cópala", precioTortilla: 19, precioMasa: 17, precioTotopos: 18 },
  { id: 26, nombre: "Abarrotes Carlim", precioTortilla: 23, precioMasa: 21, precioTotopos: 18 },
  { id: 27, nombre: "Abarrotes Shaddai", precioTortilla: 20, precioMasa: 18, precioTotopos: 18 },
  { id: 28, nombre: "Abarrotes Luna", precioTortilla: 23, precioMasa: 21, precioTotopos: 18 },
  { id: 29, nombre: "Pollos Señor de Albaterra", precioTortilla: 21, precioMasa: 19, precioTotopos: 18 },
  { id: 30, nombre: "Abarrotes Rafa", precioTortilla: 21, precioMasa: 19, precioTotopos: 18 },
  { id: 31, nombre: "Abarrotes Marisol", precioTortilla: 22, precioMasa: 20, precioTotopos: 18 },
  { id: 32, nombre: "Tienda Verde", precioTortilla: 22, precioMasa: 20, precioTotopos: 18 },
  { id: 33, nombre: "Abarrotes Fátima", precioTortilla: 20, precioMasa: 18, precioTotopos: 18 },
  { id: 34, nombre: "Abarrotes de La Esquinita", precioTortilla: 20, precioMasa: 18, precioTotopos: 18 },
  { id: 35, nombre: "Abarrotes de la Comisaría", precioTortilla: 23, precioMasa: 21, precioTotopos: 18 },
  { id: 36, nombre: "Tienda Nueva del Mesón", precioTortilla: 22, precioMasa: 20, precioTotopos: 18 },
  { id: 37, nombre: "Abarrotes Martha", precioTortilla: 23, precioMasa: 21, precioTotopos: 18 },
  { id: 38, nombre: "Abarrotes Robles", precioTortilla: 21, precioMasa: 19, precioTotopos: 18 },
  { id: 39, nombre: "Charl's", precioTortilla: 22, precioMasa: 20, precioTotopos: 18 },
  { id: 40, nombre: "Tienda Nueva Valle del Sol", precioTortilla: 22, precioMasa: 20, precioTotopos: 18 },
  { id: 41, nombre: "Tienda de Dani Mirador", precioTortilla: 22, precioMasa: 20, precioTotopos: 18 },
  { id: 42, nombre: "Carnicería del Chino", precioTortilla: 20, precioMasa: 20, precioTotopos: 18 },
  { id: 43, nombre: "Abajo de con Doña Mary", precioTortilla: 23, precioMasa: 21, precioTotopos: 18 },
  { id: 44, nombre: "Abarrotes Águila", precioTortilla: 21, precioMasa: 19, precioTotopos: 18 },
  { id: 45, nombre: "Coto 5", precioTortilla: 23, precioMasa: 21, precioTotopos: 18 },
  { id: 46, nombre: "Abarrotes La Vecinita", precioTortilla: 20, precioMasa: 18, precioTotopos: 18 },
  { id: 47, nombre: "Abarrotes del Comedor", precioTortilla: 21, precioMasa: 19, precioTotopos: 18 },
  { id: 48, nombre: "Lucy Tacos", precioTortilla: 26, precioMasa: 0, precioTotopos: 0 },
];

export default tiendas;